### ISSUE TITLE
Models are not set up

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p4-validation-flask-sqlalchemy-validations-lab#1]
### Canvas Link

https://learning.flatironschool.com/courses/6182/assignments/211188?module_item_id=486871

### Concern

Our instructions indicate that the models are already set up for students, and that all they have to do is run `alembic upgrade head`. We actually haven't filled out any information for the models thus far. Also our directions are weirdly worded: 

> 
> This project has starter code for a couple of models, Author and Post. To get set up, run:
>
> This is a test-driven lab. Run pipenv install to create your virtual environment and pipenv shell to enter the virtual environment.
> 
> To generate a database using the provided models, from lib/ run:
> 
> $ alembic upgrade head

**Comment by Matt-Eva** [comment]
Also, we don't instruct students as to what columns they should be adding to their models, or what datatypes those columns should use. I imagine that this is due to the fact that we were planning on having the models built out for them, but if we want them to build out their own models, we'll probably want to give them those details.

**Comment by pgill97** [comment]
@professor-ben  Holding off on this issue because I will change the SQLAlchemy validation stuff to use Flask-sqlalchemy then I will update this lab.

**Comment by sheenasany** [comment]
Opening this one back up again because the previous issue of the instructions stating that the lab has starter code for the Author and Post models is still not true. When opening the lab the models are empty. There is also no instruction as to what datatypes the columns should be as Matt stated previously. 

Please either include the starter code or include instructions on what to add for the models before running `flask db upgrade`. Currently there are no migrations created, so they would need to run `flask  db revision --autogenerate -m "<your comment>"` beforehand as well in order to run the migrations. Otherwise the tests will fail. 

Order of operations: 
- Have starter code for the models already set up || include instructions on what to include for each column of the models to build out 
- Run   `flask  db revision --autogenerate -m "<your comment>"`
- Then run  `flask db upgrade`
- Then run pytest and continue the lab as instructed.

**Comment by pgill97** [comment]
Added starter code to models and instructions on creating a migration.
